name = "Cifti"
uuid = "8ea9d706-23f2-4b5b-89c7-93bb3bdaf29f"
authors = ["Michael Myers"]
version = "1.0.0-DEV"

[deps]
Chain = "8be319e6-bccf-4806-a6f7-6fae938471bc"
EzXML = "8f5d6c58-4d21-5cfd-889c-e3ad7ee6a615"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"

[compat]
julia = "1.8.3"
Chain = "0.5"
EzXML = "1.1"
OrderedCollections = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
