name = "Cifti"
uuid = "8ea9d706-23f2-4b5b-89c7-93bb3bdaf29f"
authors = ["Michael Myers"]
version = "1.0.0-DEV"

[compat]
julia = "1.8.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
