name = "CIFTI"
uuid = "8026ff91-9e86-4f19-bd27-c139e9e8bf7a"
authors = ["Michael Myers"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
